// nombre canónico -> [acabado, familia cromática, nombre en español]
export const COLORES = {
  "Candy White": ["sólido", "Blanco", "Blanco Candy"],
  "Pure White": ["sólido", "Blanco", "Blanco Puro"],
  "Oryx White Perlado": ["perlado", "Blanco", "Blanco Oryx"],
  "Cristal White": ["perlado", "Blanco", "Blanco Cristal"],
  "Campanella White": ["sólido", "Blanco", "Blanco Campanella"],
  "Glacier White": ["metalizado", "Blanco", "Blanco Glaciar"],
  "White Silver": ["metalizado", "Blanco", "Blanco Plata"],
  "Ivory White": ["sólido", "Blanco", "Blanco Marfil"],
  "Reflex Silver": ["metalizado", "Plata", "Plata Reflex"],
  "Tungsten Silver": ["metalizado", "Plata", "Plata Tungsteno"],
  "Pyrite Silver": ["metalizado", "Plata", "Plata Pirita"],
  "Sky Silver": ["metalizado", "Plata", "Plata Sky"],
  "Scale Silver": ["metalizado", "Plata", "Plata Escama"],
  "Mono Silver": ["metalizado", "Plata", "Plata Mono"],
  "Silver Leaf": ["metalizado", "Plata", "Plata Hoja"],
  "Platinum Grey": ["metalizado", "Gris", "Gris Platino"],
  "Urano Grey": ["sólido", "Gris", "Gris Urano"],
  "Indium Grey": ["metalizado", "Gris", "Gris Indio"],
  "United Grey": ["metalizado", "Gris", "Gris United"],
  "Dolphin Grey": ["metalizado", "Gris", "Gris Delfín"],
  "Limestone Grey": ["metalizado", "Gris", "Gris Caliza"],
  "Moonstone Grey": ["sólido", "Gris", "Gris Piedra Lunar"],
  "Manganese Grey": ["metalizado", "Gris", "Gris Manganeso"],
  "Carbon Steel Grey": ["metalizado", "Gris", "Gris Acero Carbono"],
  "Pure Grey": ["sólido", "Gris", "Gris Puro"],
  "Ascot Grey": ["metalizado", "Gris", "Gris Ascot"],
  "Blade Silver": ["metalizado", "Gris", "Gris Blade"],
  "Anthracite Blue": ["metalizado", "Gris", "Gris Antracita"],
  "Black Uni": ["sólido", "Negro", "Negro Uni"],
  "Deep Black Perlado": ["perlado", "Negro", "Negro Profundo"],
  "Grenadilla Black": ["metalizado", "Negro", "Negro Grenadilla"],
  "Ninja Black": ["perlado", "Negro", "Negro Ninja"],
  "Black Magic Perlado": ["perlado", "Negro", "Negro Magia"],
  "Atlantic Blue": ["metalizado", "Azul", "Azul Atlántico"],
  "Shadow Blue": ["metalizado", "Azul", "Azul Sombra"],
  "Night Blue": ["metalizado", "Azul", "Azul Noche"],
  "Reef Blue": ["metalizado", "Azul", "Azul Arrecife"],
  "Lapiz Blue": ["metalizado", "Azul", "Azul Lapiz"],
  "Rising Blue": ["metalizado", "Azul", "Azul Rising"],
  "Silk Blue": ["metalizado", "Azul", "Azul Seda"],
  "Ravenna Blue": ["metalizado", "Azul", "Azul Ravenna"],
  "Costa Azul": ["metalizado", "Azul", "Costa Azul"],
  "Cornflower Blue": ["sólido", "Azul", "Azul Aciano"],
  "Nautic Blue": ["metalizado", "Azul", "Azul Náutico"],
  "Denim Blue": ["sólido", "Azul", "Azul Denim"],
  "Stonewashed Blue": ["metalizado", "Azul", "Azul Lavado"],
  "Dusk Blue": ["metalizado", "Azul", "Azul Crepúsculo"],
  "Anemone Blue": ["metalizado", "Azul", "Azul Anémona"],
  "Blue Graphite": ["metalizado", "Azul", "Azul Grafito"],
  "Starlight Blue": ["metalizado", "Azul", "Azul Estelar"],
  "Aurora Blue": ["metalizado", "Azul", "Azul Aurora"],
  "Makena Turquoise": ["metalizado", "Turquesa", "Turquesa Makena"],
  "Tornado Red": ["sólido", "Rojo", "Rojo Tornado"],
  "Flash Red": ["sólido", "Rojo", "Rojo Flash"],
  "Mars Red": ["sólido", "Rojo", "Rojo Marte"],
  "Salsa Red": ["sólido", "Rojo", "Rojo Salsa"],
  "Sunset Red": ["metalizado", "Rojo", "Rojo Atardecer"],
  "Kings Red": ["metalizado", "Rojo", "Rojo Kings"],
  "Fortana Red": ["metalizado", "Rojo", "Rojo Fortana"],
  "Wild Cherry Red": ["metalizado", "Rojo", "Rojo Cereza"],
  "Aurora Red": ["metalizado", "Rojo", "Rojo Aurora"],
  "Spice Red": ["metalizado", "Rojo", "Rojo Especia"],
  "Habanero Orange": ["metalizado", "Naranja", "Naranja Habanero"],
  "Copper Orange": ["metalizado", "Naranja", "Naranja Cobre"],
  "Energetic Orange": ["metalizado", "Naranja", "Naranja Energético"],
  "Kurkuma Yellow": ["metalizado", "Amarillo", "Amarillo Cúrcuma"],
  "Ginster Yellow": ["sólido", "Amarillo", "Amarillo Ginster"],
  "Turmeric Yellow": ["metalizado", "Amarillo", "Amarillo Turmérico"],
  "Sunflower Yellow": ["sólido", "Amarillo", "Amarillo Girasol"],
  "Pomelo Yellow": ["sólido", "Amarillo", "Amarillo Pomelo"],
  "Lemon Yellow": ["sólido", "Amarillo", "Amarillo Limón"],
  "Lime Yellow": ["sólido", "Amarillo", "Amarillo Lima"],
  "Viper Green": ["metalizado", "Verde", "Verde Víbora"],
  "Bottle Green": ["metalizado", "Verde", "Verde Botella"],
  "Lime Green": ["metalizado", "Verde", "Verde Lima"],
  "Bay Leaf Green": ["metalizado", "Verde", "Verde Laurel"],
  "Peridot Green": ["metalizado", "Verde", "Verde Peridoto"],
  "Toffee Brown": ["metalizado", "Marrón", "Marrón Toffee"],
  "Chestnut Brown": ["metalizado", "Marrón", "Marrón Castaño"],
  "Dark Bronze": ["metalizado", "Marrón", "Bronce Oscuro"],
  "Titanium Beige": ["metalizado", "Beige", "Beige Titanio"],
  "Sand Gold": ["metalizado", "Dorado", "Dorado Arena"],
  "Cashmere Brown": ["metalizado", "Marrón", "Marrón Cachemira"],
  "Aquamarine Blue": ["metalizado", "Azul", "Azul Aguamarina"],
  "Aquarius Blue": ["metalizado", "Azul", "Azul Acuario"],
  "Biscay Blue": ["metalizado", "Azul", "Azul Vizcaya"],
  "Deep Blue Pearl": ["perlado", "Azul", "Azul Profundo"],
  "Tourmaline Blue": ["metalizado", "Azul", "Azul Turmalina"],
  "Nightshade Blue": ["metalizado", "Azul", "Azul Nocturno"],
  "Canyon Grey": ["metalizado", "Gris", "Gris Cañón"],
  "Silicon Grey": ["metalizado", "Gris", "Gris Silicio"],
  "Cherry Red": ["metalizado", "Rojo", "Rojo Cereza"],
  "Malbec Red": ["metalizado", "Rojo", "Rojo Malbec"],
  "Persimmon Red": ["metalizado", "Rojo", "Rojo Caqui"],
  "Ultra Violet": ["metalizado", "Púrpura", "Violeta"],
  "Copper Bronze": ["metalizado", "Marrón", "Bronce Cobre"],
  "Mojave Beige": ["metalizado", "Beige", "Beige Mojave"],
  "Sechura Beige": ["metalizado", "Beige", "Beige Sechura"],
  "Safari Uni": ["sólido", "Beige", "Beige Safari"]
};
