// Detalle de las ediciones especiales más relevantes.
// n = nombre exacto tal y como aparece en el campo ed: de los modelos
export default [
{ n:"Golf GTI Edition 30", anio:2006, uds:"Serie limitada, sin cifra oficial global", merc:["Europa"],
  det:"Celebró los treinta años del GTI con 230 CV del 2.0 TFSI, 30 más que el GTI normal, diferencial electrónico XDS y detalles rojos en parrilla e interior.",
  col:["Candy White","Black Uni","Tornado Red","United Grey","Reflex Silver"] },
{ n:"Golf GTI Pirelli", anio:2007, uds:"Alrededor de 1.500 unidades", merc:["Europa"],
  det:"Homenaje al GTI Pirelli de 1983. Mismos 230 CV de la Edition 30, llantas de 18 pulgadas con dibujo de neumático y tapicería con relieve de banda de rodadura.",
  col:["Candy White","Black Uni","Tornado Red","Reflex Silver"] },
{ n:"Golf R32 Mk5", anio:2005, uds:"Producción de serie limitada en el tiempo", merc:["Europa","Norteamérica","Australia"],
  det:"VR6 de 3.2 litros y 250 CV, tracción 4Motion y cambio DSG de doble embrague, el primero en un Volkswagen de gran serie. Escape central doble.",
  col:["Deep Blue Pearl","United Grey","Black Uni","Reflex Silver","Candy White"] },
{ n:"Golf GTI Edition 35", anio:2011, uds:"Serie limitada", merc:["Europa"],
  det:"Treinta y cinco años del GTI: 235 CV, faros bixenón de serie y llantas Watkins Glen de 18 pulgadas.",
  col:["Candy White","Deep Black Perlado","Tornado Red","Reflex Silver"] },
{ n:"Golf R Mk6", anio:2009, uds:"Modelo de gama, no limitado", merc:["Europa","Norteamérica","Australia","Latinoamérica"],
  det:"Primer R sin VR6: 2.0 TSI de 270 CV, 4Motion Haldex y frenos mayores. Sustituyó al R32 en lo alto de la gama.",
  col:["Candy White","Deep Black Perlado","Rising Blue","Reflex Silver","United Grey"] },
{ n:"Golf GTI Clubsport", anio:2016, uds:"Serie limitada por año de modelo", merc:["Europa","Australia"],
  det:"Cuarenta años del GTI. 265 CV con función boost de 290 CV durante diez segundos, aerodinámica específica y ajuste de chasis propio.",
  col:["Pure White","Deep Black Perlado","Tornado Red","Limestone Grey","Oryx White Perlado"] },
{ n:"Golf GTI Clubsport S", anio:2016, uds:"400 unidades", merc:["Europa"],
  det:"310 CV, dos plazas, sin asientos traseros y con barra antivuelco de refuerzo. Marcó 7:49,21 en Nürburgring, récord de tracción delantera en su momento.",
  col:["Pure White","Deep Black Perlado","Tornado Red"] },
{ n:"Golf GTI TCR", anio:2018, uds:"Serie limitada", merc:["Europa"],
  det:"Versión de calle del GTI de competición TCR: 290 CV, diferencial autoblocante VAQ y limitador opcional elevado a 260 km/h.",
  col:["Pure White","Deep Black Perlado","Tornado Red","Pure Grey"] },
{ n:"Golf GTI Clubsport 45", anio:2021, uds:"Serie limitada", merc:["Europa"],
  det:"Cuarenta y cinco años del GTI sobre base Mk8 Clubsport: 300 CV, escape Akrapovič opcional y paquete Race con limitador a 267 km/h.",
  col:["Pure White","Deep Black Perlado","Kings Red","Moonstone Grey"] },
{ n:"Golf R 20 Years", anio:2022, uds:"Serie limitada", merc:["Europa","Norteamérica"],
  det:"Veinte años de la sigla R desde el Golf R32. 333 CV, la potencia más alta jamás dada a un Golf de serie, con modo Drift y escape Akrapovič de serie.",
  col:["Lapiz Blue","Deep Black Perlado","Pure White"] },
{ n:"Golf GTI Edition 50", anio:2025, uds:"Serie limitada", merc:["Europa"],
  det:"Cincuenta años del GTI con 325 CV, el GTI más potente de la historia, y un paquete Nürburgring con neumáticos semislick.",
  col:["Pure White","Deep Black Perlado","Kings Red","Moonstone Grey"] },
{ n:"Polo R WRC Street", anio:2013, uds:"2.500 unidades", merc:["Europa"],
  det:"Homologación comercial del Polo R WRC de rallyes: 1.4 TSI biturbo de 220 CV, chasis rebajado 15 mm y decoración específica.",
  col:["Pure White","Deep Black Perlado","Flash Red","Reflex Silver"] },
{ n:"Polo GTI Edition 25", anio:2023, uds:"Serie limitada", merc:["Europa"],
  det:"Veinticinco años del Polo GTI: 207 CV, suspensión Sport Select y llantas Faro de 18 pulgadas con detalles rojos.",
  col:["Pure White","Deep Black Perlado","Kings Red"] },
{ n:"Up! GTI", anio:2018, uds:"Modelo de gama limitado en el tiempo", merc:["Europa"],
  det:"Recuperó la receta del GTI original: 115 CV, 1.070 kg, tapicería de cuadros escoceses y franja roja en la parrilla.",
  col:["Pure White","Deep Black Perlado","Tornado Red","Reflex Silver"] },
{ n:"Beetle GSR", anio:2013, uds:"3.500 unidades en todo el mundo", merc:["Europa","Norteamérica"],
  det:"Homenaje al Gelb-Schwarzer Renner de 1973: amarillo y negro obligatorios, 210 CV y placa numerada en el salpicadero.",
  col:["Sunflower Yellow"] },
{ n:"Beetle Final Edition", anio:2019, uds:"Serie final", merc:["Europa","Norteamérica","Latinoamérica"],
  det:"Cerró 81 años de Escarabajo en cualquiera de sus formas, con acabados SE y SEL y dos colores exclusivos.",
  col:["Safari Uni","Stonewashed Blue","Pure White","Deep Black Perlado"] },
{ n:"Beetle Dune", anio:2016, uds:"Modelo de gama", merc:["Europa","Norteamérica"],
  det:"Carrocería elevada 10 mm, vías ensanchadas y protecciones de plástico, inspirada en los Baja Bug del desierto.",
  col:["Sand Gold","Pure White","Deep Black Perlado"] },
{ n:"Beetle Denim", anio:2016, uds:"2.000 unidades", merc:["Norteamérica"],
  det:"Cabrio con capota azul tipo tejano y tapicería que imita la mezclilla, guiño al Beetle Jeans de 1974.",
  col:["Denim Blue","Pure White"] },
{ n:"Beetle Fender Edition", anio:2012, uds:"Serie limitada", merc:["Europa","Norteamérica"],
  det:"Equipo de sonido Fender de 400 W, salpicadero con acabado de guitarra sunburst y llantas específicas.",
  col:["Deep Black Perlado","Pure White","Toffee Brown"] },
{ n:"New Beetle Última Edición", anio:2010, uds:"1.500 unidades", merc:["Latinoamérica"],
  det:"Cerró la producción en Puebla del New Beetle con placa numerada, llantas cromadas y florero de serie.",
  col:["Aquarius Blue","Ivory White"] },
{ n:"Scirocco R", anio:2009, uds:"Modelo de gama", merc:["Europa","China","Australia"],
  det:"265 CV del 2.0 TSI, diferencial XDS y suspensión rebajada 15 mm. La versión más potente del coupé.",
  col:["Rising Blue","Deep Black Perlado","Pure White","Tornado Red","Viper Green"] },
{ n:"Scirocco GTS", anio:2013, uds:"Serie limitada", merc:["Europa","China"],
  det:"Recuperó las bandas negras longitudinales del Scirocco GTS de 1982 sobre el 2.0 TSI de 220 CV.",
  col:["Pure White","Deep Black Perlado","Tornado Red","Viper Green"] },
{ n:"Scirocco GT24", anio:2009, uds:"Serie limitada", merc:["Europa"],
  det:"Homenaje al Scirocco ganador de su categoría en las 24 Horas de Nürburgring, con decoración de competición.",
  col:["Candy White","Deep Black Perlado"] },
{ n:"Passat R36", anio:2007, uds:"Modelo de gama limitado en el tiempo", merc:["Europa","Australia"],
  det:"VR6 de 3.6 litros y 300 CV con 4Motion y DSG. Sigue siendo el Passat de serie más potente que se ha vendido.",
  col:["Deep Black Perlado","Candy White","Biscay Blue","Reflex Silver"] },
{ n:"Arteon R", anio:2020, uds:"Modelo de gama", merc:["Europa","Australia"],
  det:"320 CV y diferencial vectorial trasero, el único R de la marca con carrocería fastback y familiar Shooting Brake.",
  col:["Lapiz Blue","Deep Black Perlado","Pure White","Kings Red"] },
{ n:"Touareg R50", anio:2007, uds:"Alrededor de 1.000 unidades", merc:["Europa","Australia","Oriente Medio"],
  det:"V10 TDI llevado a 350 CV y 850 Nm por Volkswagen Individual, con suspensión rebajada y llantas de 21 pulgadas.",
  col:["Deep Black Perlado","Reflex Silver","Candy White"] },
{ n:"Touareg R eHybrid", anio:2020, uds:"Modelo de gama", merc:["Europa","China"],
  det:"462 CV combinados entre el V6 TSI y el motor eléctrico. El Volkswagen de serie más potente jamás vendido bajo la sigla R.",
  col:["Oryx White Perlado","Deep Black Perlado","Silicon Grey","Malbec Red"] },
{ n:"Tiguan R", anio:2021, uds:"Modelo de gama", merc:["Europa","Australia"],
  det:"320 CV, vectorización por par en el eje trasero y escape Akrapovič opcional. Primer SUV compacto de la marca con la letra R.",
  col:["Lapiz Blue","Deep Black Perlado","Pure White","Kings Red"] },
{ n:"T-Roc R", anio:2019, uds:"Modelo de gama", merc:["Europa","Australia"],
  det:"300 CV con launch control y modo Race. Comparte mecánica con el Golf R Mk7.5 en carrocería alta.",
  col:["Lapiz Blue","Deep Black Perlado","Pure White","Kings Red"] },
{ n:"T-Roc Cabriolet", anio:2020, uds:"Modelo de gama", merc:["Europa"],
  det:"Primer SUV descapotable de Volkswagen, con capota de lona eléctrica y solo dos puertas.",
  col:["Pure White","Deep Black Perlado","Energetic Orange","Ravenna Blue","Kings Red"] },
{ n:"Amarok Canyon", anio:2013, uds:"Serie limitada por mercado", merc:["Europa","Latinoamérica"],
  det:"Naranja de carrocería, estribos laterales, arco antivuelco decorativo y detalles negros mate.",
  col:["Copper Orange"] },
{ n:"Amarok W580 (Australia)", anio:2021, uds:"Serie limitada australiana", merc:["Australia"],
  det:"Desarrollada por Walkinshaw para Australia con suspensión, dirección y estética específicas sobre el V6 de 3.0 TDI.",
  col:["Deep Black Perlado","Candy White","Reflex Silver"] },
{ n:"Amarok PanAmericana", anio:2023, uds:"Modelo de gama", merc:["Europa","Latinoamérica","Sudáfrica"],
  det:"Acabado campero de la segunda Amarok, con protecciones, barras de techo y llantas de 18 pulgadas para neumático de perfil alto.",
  col:["Mojave Beige","Deep Black Perlado","Pure White","Kings Red"] },
{ n:"Gol Last Edition", anio:2023, uds:"Serie final", merc:["Latinoamérica"],
  det:"Cerró 43 años y más de ocho millones de unidades del Gol, con emblemas conmemorativos y equipamiento del acabado alto.",
  col:["Cristal White","Ninja Black","Platinum Grey"] },
{ n:"Jetta GLI 40th Anniversary Edition", anio:2024, uds:"Serie limitada", merc:["Norteamérica"],
  det:"Cuarenta años del GLI: llantas negras de 18 pulgadas, techo negro y detalles rojos, sobre el 2.0 TSI de 228 CV.",
  col:["Deep Black Perlado","Pure White","Kings Red"] },
{ n:"Virtus GTS", anio:2023, uds:"Modelo de gama", merc:["Latinoamérica"],
  det:"Recuperó la sigla GTS brasileña de los años ochenta con el 1.4 TSI de 150 CV y suspensión más firme.",
  col:["Fortana Red","Deep Black Perlado","Pure White","Platinum Grey"] },
{ n:"Nivus GTS", anio:2023, uds:"Modelo de gama", merc:["Latinoamérica"],
  det:"Versión deportiva del SUV coupé brasileño con el 1.4 TSI de 150 CV, techo negro y detalles rojos.",
  col:["Fortana Red","Deep Black Perlado","Pure White"] },
{ n:"T-Cross GTS", anio:2024, uds:"Modelo de gama", merc:["Latinoamérica"],
  det:"El GTS aplicado al SUV urbano más vendido de Brasil: 150 CV, llantas de 17 pulgadas y calibración de chasis propia.",
  col:["Fortana Red","Deep Black Perlado","Pure White"] },
{ n:"ID.3 1ST Edition", anio:2020, uds:"30.000 unidades", merc:["Europa"],
  det:"Serie de lanzamiento del primer MEB, con equipamiento cerrado en tres niveles (1ST, 1ST Plus y 1ST Max) y reserva por adelantado.",
  col:["Glacier White","Moonstone Grey","Makena Turquoise","Manganese Grey"] },
{ n:"ID. Buzz 1ST Edition", anio:2022, uds:"Serie de lanzamiento", merc:["Europa"],
  det:"Lanzamiento del Bulli eléctrico con carrocería bicolor de serie y equipamiento cerrado.",
  col:["Lime Yellow","Bay Leaf Green","Starlight Blue","Energetic Orange","Candy White"] },
{ n:"ID. Buzz California", anio:2025, uds:"Modelo de gama", merc:["Europa"],
  det:"Camper eléctrica sobre el ID. Buzz de batalla larga, con techo elevable y cocina, sin motor de combustión por primera vez en la historia del California.",
  col:["Candy White","Bay Leaf Green","Starlight Blue","Mono Silver"] },
{ n:"XL1 (serie de 250 unidades)", anio:2013, uds:"250 unidades", merc:["Europa"],
  det:"Híbrido enchufable diésel de 0,9 l/100 km homologados, monocasco de fibra de carbono, puertas de ala de gaviota y 795 kg.",
  col:["Oryx White Perlado","Deep Black Perlado","Reflex Silver"] },
{ n:"Citi Golf Mk1 Limited Edition", anio:2009, uds:"1.000 unidades", merc:["Sudáfrica"],
  det:"Serie final que cerró 25 años del Citi Golf y, con ellos, la producción del Golf Mk1 en el mundo.",
  col:["Candy White","Black Uni","Tornado Red"] },
{ n:"Multivan PanAmericana", anio:2018, uds:"Modelo de gama", merc:["Europa"],
  det:"Acabado campero de la Multivan con tracción 4Motion, suspensión elevada y protecciones, inspirado en la ruta panamericana.",
  col:["Starlight Blue","Deep Black Perlado","Candy White","Bay Leaf Green"] },
{ n:"Grand California", anio:2019, uds:"Modelo de gama", merc:["Europa"],
  det:"Camper integral sobre Crafter con baño completo y cama transversal, en dos longitudes: 600 y 680 centímetros.",
  col:["Candy White","Reflex Silver","Bay Leaf Green"] },
{ n:"Touareg Edition X", anio:2017, uds:"Serie limitada", merc:["Europa"],
  det:"Quince años del Touareg, con equipamiento máximo, llantas de 21 pulgadas y detalles cromados oscuros.",
  col:["Deep Black Perlado","Pure White","Reflex Silver"] },
{ n:"Passat GT", anio:2018, uds:"Serie limitada", merc:["Norteamérica"],
  det:"El Passat estadounidense con el VR6 de 3.6 litros, estética R-Line, suspensión rebajada y detalles rojos.",
  col:["Pure White","Deep Black Perlado","Aurora Red"] },
{ n:"Jetta Clásico Última Edición", anio:2015, uds:"Serie final", merc:["Latinoamérica"],
  det:"Cerró en México la carrera del Jetta Mk4, que allí se vendió trece años más que en Europa.",
  col:["Candy White","Reflex Silver","Platinum Grey"] }
];
